# Generated by Django 5.0 on 2023-12-11 16:58

import vendors.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vendor_code', models.CharField(blank=True, default=vendors.helpers.generate_unique_code, max_length=255, null=True, unique=True)),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True)),
                ('quality_rating_avg', models.FloatField(blank=True, null=True)),
                ('average_response_time', models.FloatField(blank=True, null=True)),
                ('fulfilment_rate', models.FloatField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'vendors',
                'db_table': 'vendor',
            },
        ),
    ]
